name: Checks

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  checks:
    uses: kaisekidev/.github/.github/workflows/checks.yml@v1
